RED-1218 replace fontawesome witn fontello
minddistrict/js.angular_xeditable pull request #1
Opened 2017-11-10 10:07 UTC by janjaapdriessen

2017-11-10 10:29 UTC, janjaapdriessen commented on js/angular_xeditable/resources/js/xeditable.js
> +Build date: 2016-12-27
PR best viewed with `?w=1`, my editor ate the whitespace

2017-11-13 09:57 UTC, richardicke commented
This is a public repo; this change will now break the package for people that use vanilla FA.

2017-11-13 11:19 UTC, janjaapdriessen commented
I reflected the fontawesome.io -> fontello.com change in the changes.txt

2017-11-16 08:04 UTC, thefunny42 requested changes
Minified version need to be updated.

2017-11-16 08:17 UTC, janjaapdriessen commented
not using these changes in the end, we override template in our own application.

2017-11-16 08:17 UTC, closed without merging